# SITE CONFIGURATION

url: "http://needtochangelater.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Emiko Dodson # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Always curious, aspiring kata master</h1>
     <p>The beginning stages of a software developer.</p>
  header_text_feature_image:
  footer_text:

  # Icons
  rss: false
  email_address: emiko.dodson@me.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: emico7 # github profile name, e.g. "madebymunsters"
  google_plus:
  instagram:
  linkedin:  https://www.linkedin.com/in/emico7 # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: #"UA-75140315-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Lora+in+the+Wild"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
